---
title: "Eval"
author: "Sem"
date: "2025-05-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(RColorBrewer)
library(dplyr)
library(stringr)
library(ggplot2)
library(viridis)
library(ggnewscale)
library(ggh4x)
library(svglite)
```

# Introduction

This .Rmd file is used to create nice plots for the report and presentation

## PHH data

```{r}
data_dir <- "C:/Users/semde/Documents/BOO_Scripts/Data/PHH_TXG-MAPr"
module_enrichment_PHH   <- readRDS(file.path(data_dir, "module_enrichment.rds"))
drw_scores_PHH <- readRDS(file.path(data_dir, "drw_scores_PHH_directed.rds"))
eg_scores_PHH <- readRDS(file.path(data_dir, "eg_score.rds"))
#sdrw_scores_PHH <- readRDS(file.path(data_dir, "sdrw_scores_PHH_directed.rds")) # not finished yet

```

## RPTEC data

```{r}
data_dir <- "C:/Users/semde/Documents/BOO_Scripts/Data/RPTEC_TXG-MAPr"
module_enrichment_RPTEC   <- readRDS(file.path(data_dir, "module_enrichment.rds"))
drw_scores_RPTEC <- readRDS(file.path(data_dir, "drw_scores_RPTEC_r0.7.rds"))
eg_scores_RPTEC <- readRDS(file.path(data_dir, "eg_score.rds"))
#sdrw_scores_RPTEC <- readRDS(file.path(data_dir, "sdrw_scores_RPTEC_directed.rds"))
```

# wGRR Outlier Summary

## PHH

```{r}
df_phh <- data.frame(
  Algorithm = c("Eigengene", "Eigengene", "wDRW", "wDRW"),
  Outlier_Direction = c("Underquantification", "Overquantification", "Underquantification", "Overquantification"),
  density = c(0.030444465, 0.001257616, 0.028, 0.000676)
)
```

```{r}
# Zorg dat 'Below fit' onder 'Above fit' komt in stacking
df_phh$Outlier_Direction <- factor(df_phh$Outlier_Direction, levels = c("Overquantification", "Underquantification"))
```


```{r}
darkblue_palette <- c("Overquantification" = "#1f78b4",
                      "Underquantification" = "#0c2c54") 

# Plot met custom palette
ggplot(df_phh, aes(x = Algorithm, y = density, fill = Outlier_Direction)) +
  geom_bar(stat = "identity") +
  labs(y = "Outlier Density", x = "Scoring Algorithm", fill = "Outlier Direction") +
  ggtitle("Outlier density above and below binomial fit (wGRR vs scoring method) in PHH") +
  theme_minimal() +
  scale_fill_manual(values = darkblue_palette)
```

## RPTEC

```{r}
df_rptec <- data.frame(
  Algorithm = c("Eigengene", "Eigengene", "wDRW", "wDRW"),
  Outlier_Direction = c("Underquantification", "Overquantification", "Underquantification", "Overquantification"),
  density = c(0.11816872, 0.02527436, 0.0802, 0.0187)
)
```

```{r}
# Zorg dat 'Below fit' onder 'Above fit' komt in stacking
df_rptec$Outlier_Direction <- factor(df_rptec$Outlier_Direction, levels = c("Overquantification", "Underquantification"))

# Plot
ggplot(df_rptec, aes(x = Algorithm, y = density, fill = Outlier_Direction)) +
  geom_bar(stat = "identity") +
  labs(y = "Outlier Density", x = "Scoring Algorithm", fill = "Outlier Direction") +
  ggtitle("Outlier density above and below binomial fit (wGRR vs scoring method) in RPTEC") +
  theme_minimal() + scale_fill_brewer(palette = "Set2")
```


# Heatmap

## PHH 

Strip for module numbers and conditions

```{r}
eg_scores_PHH <- eg_scores_PHH %>%
  mutate(chemical = str_extract(sample_id, "(?<=TG_HPHH_SINGLE_)[^_]+")) %>% 
  select(abs_eg_score, chemical, module_number)
```

### drw_score df

```{r}
drw_scores_PHH <- drw_scores_PHH %>%
  mutate(chemical = str_extract(condition_id, "(?<=TG_HPHH_SINGLE_)[^_]+")) %>% 
  mutate(module_number=module_nr) %>%
  select(chemical, drw_zscore, module_number)
```

## RPTEC

Strip for module numbers and conditions

### eg_score df

Strip for module numbers

```{r}
eg_scores_RPTEC_clean <- eg_scores_RPTEC %>%
  mutate(
    chemical = str_extract(sample_id, "(?<=LU_HRPTECTERT1_SINGLE_)[^_]+"),
    time = factor(str_extract(sample_id, "_T[12]") %>% str_remove("_")),
    concentration = factor(str_extract(sample_id, "C[0-9]+"))
  ) %>%
  select(eg_score, chemical, time, concentration, module_number)
```

### drw_score df

```{r}
drw_scores_RPTEC_clean <- drw_scores_RPTEC %>%
  mutate(
    chemical = str_extract(condition_id, "(?<=LU_HRPTECTERT1_SINGLE_)[^_]+"),
    base_string = substr(condition_id, 1, nchar(condition_id) - 3),
    
    time = substr(base_string, nchar(base_string) - 1, nchar(base_string)),
    time = factor(time, levels = c("T1", "T2", "T3")),
    
    # Zet om naar factor
    concentration = factor(str_extract(condition_id, "C[0-9]+")),
    module_number = module_nr
  ) %>%
  select(chemical, time, concentration, drw_zscore, module_number)
```

```{r}
summary(drw_scores_RPTEC_clean)
```


### Preprocessing Heatmap

```{r}
selected_chemicals <- c("DOXORUBICIN", "MITOMYCIN", "LEADACETATE", "GENTAMYCIN", 
                        "DICHLOROVINYLCYSTEINE", "CYCLOSPORINA", "OMEPRAZOLE", "CADMIUMDICHLORIDE")

selected_modules <- c(12, 263, 35, 260, 33, 40, 109, 162, 211, 235,
                      15, 44, 46, 254, 16, 19, 134, 240, 288, 50, 56)

# Filter DRW
drw_filtered <- drw_scores_RPTEC_clean %>%
  filter(chemical %in% selected_chemicals,
         module_number %in% selected_modules)

# Filter EG
eg_filtered <- eg_scores_RPTEC_clean %>%
  filter(chemical %in% selected_chemicals,
         module_number %in% selected_modules)
```


### Plot Heatmap

```{r}
drw_filtered <- drw_filtered %>%
  mutate(
    chemical = factor(chemical, levels = selected_chemicals),
    time = factor(time, levels = c("T1", "T2", "T3")),
    concentration = factor(concentration, levels = c("C1", "C2", "C3")),
    module_number = factor(module_number, levels = sort(selected_modules))
  )
```


```{r}
# Plot
p <- ggplot(drw_filtered, aes(x = concentration, y = module_number, fill = drw_zscore)) +
  geom_tile(color = "gray80", width = 0.95, height = 0.95) +  # grid zichtbaar met grijze rand
  facet_nested(
    ~ chemical + time,
    nest_line = element_line(linewidth = 0.3),
    switch = "x"
  ) +
  scale_fill_gradient2(
    low = "#2166AC", mid = "white", high = "#B2182B",
    midpoint = 0, name = "DRW z-score",
    limits = c(-max(abs(drw_filtered$drw_zscore)), max(abs(drw_filtered$drw_zscore)))
  ) +
  labs(x = NULL, y = "Module") +
  coord_fixed() +
  theme_minimal(base_size = 10) +
  theme(
    axis.text.x = element_text(angle = 0, hjust = 0.5, size = 6),
    axis.text.y = element_text(size = 6),
    strip.placement = "outside",
    strip.text.x = element_text(size = 8),
    panel.spacing.x = unit(0.3, "lines"),
    panel.grid = element_blank(),
    legend.position = "right"
  )

print(p)
```

```{r}
# Sla op als PDF (geschikt voor Inkscape)
ggsave("heatmap_base.svg", plot = p, width = 12, height = 6, device = "svg")
```



